name: Functional_test

on:
  push:
    paths: '**.py'
  
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}/lib/python${{ matrix.python-version }}/site-packages/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: package paths
      run: |
        python -c 'import sys; print(sys.path)'
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/cache/save@v3
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: ${{ env.pythonLocation }}/lib/python${{ matrix.python-version }}/site-packages/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Run test
      run: | 
        python tests/testdpp.py